### ISSUE TITLE
error: [Transaction]: Error: No valid responses from any peers.

### ISSUE THREAD

**Issue by thangld322** [hyperledger/fabric-samples#566]
I follow the guide here: https://hyperledger-fabric.readthedocs.io/en/release-2.2/write_first_app.html
When I run `node app.js` command, it gives me this error:
```
Loaded the network configuration located at /home/thangld/go/src/github.com/thangld322/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/connection-org1.json
Built a CA Client named ca-org1
Built a file system wallet at /home/thangld/go/src/github.com/thangld322/fabric-samples/asset-transfer-basic/application-javascript/wallet
Successfully enrolled admin user and imported it into the wallet
Successfully registered and enrolled user appUser and imported it into the wallet

--> Submit Transaction: InitLedger, function creates the initial set of assets on the ledger
2021-12-20T06:58:03.931Z - error: [Transaction]: Error: No valid responses from any peers. Errors:
    peer=peer0.org2.example.com:9051, status=500, message=error in simulation: failed to execute transaction 55cca2b4b112e8feaa128091a003dfafacb45b98a11bf3729e88e34610d1bb32: could not launch chaincode basic_1.0:b359a077730d7f44d6a437ad49d1da951f6a01c6d1eed4f85b8b1f5a08617fe7: error starting container: error starting container: API error (404): network _test not found
    peer=peer0.org1.example.com:7051, status=500, message=error in simulation: failed to execute transaction 55cca2b4b112e8feaa128091a003dfafacb45b98a11bf3729e88e34610d1bb32: could not launch chaincode basic_1.0:b359a077730d7f44d6a437ad49d1da951f6a01c6d1eed4f85b8b1f5a08617fe7: error starting container: error starting container: API error (404): network _test not found
    at newEndorsementError (/home/thangld/go/src/github.com/thangld322/fabric-samples/asset-transfer-basic/application-javascript/node_modules/fabric-network/lib/transaction.js:74:12)
    at getResponsePayload (/home/thangld/go/src/github.com/thangld322/fabric-samples/asset-transfer-basic/application-javascript/node_modules/fabric-network/lib/transaction.js:41:23)
    at Transaction.submit (/home/thangld/go/src/github.com/thangld322/fabric-samples/asset-transfer-basic/application-javascript/node_modules/fabric-network/lib/transaction.js:255:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async main (/home/thangld/go/src/github.com/thangld322/fabric-samples/asset-transfer-basic/application-javascript/app.js:118:4)
******** FAILED to run the application: Error: No valid responses from any peers. Errors:
    peer=peer0.org2.example.com:9051, status=500, message=error in simulation: failed to execute transaction 55cca2b4b112e8feaa128091a003dfafacb45b98a11bf3729e88e34610d1bb32: could not launch chaincode basic_1.0:b359a077730d7f44d6a437ad49d1da951f6a01c6d1eed4f85b8b1f5a08617fe7: error starting container: error starting container: API error (404): network _test not found
    peer=peer0.org1.example.com:7051, status=500, message=error in simulation: failed to execute transaction 55cca2b4b112e8feaa128091a003dfafacb45b98a11bf3729e88e34610d1bb32: could not launch chaincode basic_1.0:b359a077730d7f44d6a437ad49d1da951f6a01c6d1eed4f85b8b1f5a08617fe7: error starting container: error starting container: API error (404): network _test not found
```
Please help!

**Comment by timo-kang** [comment]
was it successful on invoking chaincode?

If so, you should see application can communicate with peers, or orderer nodes.
first of all, try put hosts on `/etc/hosts` file.
you can see the docker internal network gateway ip addr via `docker inspect $network`

**Comment by thangld322** [comment]
> was it successful on invoking chaincode?

It was. 
I just found out that the problem was this line in docker-compose-test-net.yaml file: 
```
- CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_test
```
COMPOSE_PROJECT_NAME was blank. Fixed it. Thanks :D

**Comment by BhargavaCreates** [comment]
@thangld322 which file or place were you able to pass a value for COMPOSE_PROJECT_NAME ? and what was the value that you passed? facing same issue
