### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jkvargas** [hyperledger/fabric-samples#571]
Maybe you guys can point me out on a solution.
When I bring network.sh up from the test-network. I realized that the ports that should be open in order to create channel are not.
Maybe I am missing something...
I appreciate any tip.
Getting some logs from the journalctl I have the following,

```
Jan 01 17:02:04 VFIEVOX3.Router systemd[1]: docker-6145a913ddcc595378fbb4a69af72113ab1b47ed9c04f5db23fd84b52eb91653.scope: Deactivated successfully.
Jan 01 17:02:04 VFIEVOX3.Router 6145a913ddcc[12462]: 2022-01-01 17:02:04.603 UTC 0001 ERRO [main] InitCmd -> Cannot run peer because could not initialize BCCSP Factories: Failed initializing BCCSP: Could not initialize BCCSP SW [Failed to initialize software key store: open /etc/hyperledger/fabric/msp/keystore: perm>
Jan 01 17:02:04 VFIEVOX3.Router gnome-shell[8782]: Removing a network device that was not added
Jan 01 17:02:04 VFIEVOX3.Router audit[38205]: NETFILTER_CFG table=nat:491 family=2 entries=1 op=nft_unregister_rule pid=38205 subj=system_u:system_r:iptables_t:s0 comm="iptables"
Jan 01 17:02:04 VFIEVOX3.Router gnome-shell[8782]: Removing a network device that was not added
Jan 01 17:02:04 VFIEVOX3.Router NetworkManager[952]: <info>  [1641056524.5934] device (vethd0e43eb): released from master device br-fe1f0078fe48
Jan 01 17:02:04 VFIEVOX3.Router kernel: br-fe1f0078fe48: port 1(vethd0e43eb) entered disabled state
Jan 01 17:02:04 VFIEVOX3.Router kernel: device vethd0e43eb left promiscuous mode
Jan 01 17:02:04 VFIEVOX3.Router audit: ANOM_PROMISCUOUS dev=vethd0e43eb prom=0 old_prom=256 auid=4294967295 uid=0 gid=0 ses=4294967295
Jan 01 17:02:04 VFIEVOX3.Router kernel: br-fe1f0078fe48: port 1(vethd0e43eb) entered disabled state
Jan 01 17:02:04 VFIEVOX3.Router dockerd[12474]: time="2022-01-01T17:02:04.582393341Z" level=warning msg="cleanup warnings time=\"2022-01-01T17:02:04Z\" level=info msg=\"starting signal loop\" namespace=moby pid=38191\n"
Jan 01 17:02:04 VFIEVOX3.Router dockerd[12474]: time="2022-01-01T17:02:04.568648897Z" level=info msg="cleaning up dead shim"
Jan 01 17:02:04 VFIEVOX3.Router dockerd[12474]: time="2022-01-01T17:02:04.568639491Z" level=warning msg="cleaning up after shim disconnected" id=95a3e54eb173b3e5fec3ff94a5f6dd826472cdbc2ae0fe4e9e9544dbc6f9f2e6 namespace=moby
Jan 01 17:02:04 VFIEVOX3.Router dockerd[12474]: time="2022-01-01T17:02:04.568453458Z" level=info msg="shim disconnected" id=95a3e54eb173b3e5fec3ff94a5f6dd826472cdbc2ae0fe4e9e9544dbc6f9f2e6
Jan 01 17:02:04 VFIEVOX3.Router dockerd[12462]: time="2022-01-01T17:02:04.568337061Z" level=info msg="ignoring event" container=95a3e54eb173b3e5fec3ff94a5f6dd826472cdbc2ae0fe4e9e9544dbc6f9f2e6 module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Jan 01 17:02:04 VFIEVOX3.Router NetworkManager[952]: <info>  [1641056524.5462] manager: (veth0d2e1ea): new Veth device (/org/freedesktop/NetworkManager/Devices/227)
Jan 01 17:02:04 VFIEVOX3.Router audit: BPF prog-id=0 op=UNLOAD
Jan 01 17:02:04 VFIEVOX3.Router systemd[1]: docker-95a3e54eb173b3e5fec3ff94a5f6dd826472cdbc2ae0fe4e9e9544dbc6f9f2e6.scope: Deactivated successfully.
Jan 01 17:02:04 VFIEVOX3.Router 95a3e54eb173[12462]:         /go/src/github.com/hyperledger/fabric/cmd/orderer/main.go:15 +0x25
Jan 01 17:02:04 VFIEVOX3.Router 95a3e54eb173[12462]: main.main()
Jan 01 17:02:04 VFIEVOX3.Router 95a3e54eb173[12462]:         /go/src/github.com/hyperledger/fabric/orderer/common/server/main.go:93 +0x267
Jan 01 17:02:04 VFIEVOX3.Router 95a3e54eb173[12462]: github.com/hyperledger/fabric/orderer/common/server.Main()
Jan 01 17:02:04 VFIEVOX3.Router 95a3e54eb173[12462]:         /go/src/github.com/hyperledger/fabric/orderer/common/server/main.go:763 +0x111
Jan 01 17:02:04 VFIEVOX3.Router 95a3e54eb173[12462]: github.com/hyperledger/fabric/orderer/common/server.loadLocalMSP(0xc0005c8000, 0xc000590870, 0x0)
Jan 01 17:02:04 VFIEVOX3.Router 95a3e54eb173[12462]:         /go/src/github.com/hyperledger/fabric/common/flogging/zap.go:74
Jan 01 17:02:04 VFIEVOX3.Router 95a3e54eb173[12462]: github.com/hyperledger/fabric/common/flogging.(*FabricLogger).Panicf(...)
Jan 01 17:02:04 VFIEVOX3.Router 95a3e54eb173[12462]:         /go/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/sugar.go:159
Jan 01 17:02:04 VFIEVOX3.Router 95a3e54eb173[12462]: go.uber.org/zap.(*SugaredLogger).Panicf(...)
Jan 01 17:02:04 VFIEVOX3.Router 95a3e54eb173[12462]:         /go/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/sugar.go:234 +0xf6
Jan 01 17:02:04 VFIEVOX3.Router 95a3e54eb173[12462]: go.uber.org/zap.(*SugaredLogger).log(0xc000574140, 0x4, 0x108c7f5, 0x22, 0xc00017f228, 0x1, 0x1, 0x0, 0x0, 0x0)
Jan 01 17:02:04 VFIEVOX3.Router 95a3e54eb173[12462]:         /go/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/zapcore/entry.go:234 +0x58d
Jan 01 17:02:04 VFIEVOX3.Router 95a3e54eb173[12462]: go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc000595bc0, 0x0, 0x0, 0x0)
Jan 01 17:02:04 VFIEVOX3.Router 95a3e54eb173[12462]: goroutine 1 [running]:
Jan 01 17:02:04 VFIEVOX3.Router 95a3e54eb173[12462]: 
Jan 01 17:02:04 VFIEVOX3.Router 95a3e54eb173[12462]: panic: Failed to get local msp config: could not initialize BCCSP Factories: Failed initializing BCCSP: Could not initialize BCCSP SW [Failed to initialize software key store: open /var/hyperledger/orderer/msp/keystore: permission denied]
Jan 01 17:02:04 VFIEVOX3.Router 95a3e54eb173[12462]: 2022-01-01 17:02:04.534 UTC 0003 PANI [orderer.common.server] loadLocalMSP -> Failed to get local msp config: could not initialize BCCSP Factories: Failed initializing BCCSP: Could not initialize BCCSP SW [Failed to initialize software key store: open /var/hyperle>
Jan 01 17:02:04 VFIEVOX3.Router 95a3e54eb173[12462]:         Admin.TLS.TLSHandshakeTimeShift = 0s
Jan 01 17:02:04 VFIEVOX3.Router 95a3e54eb173[12462]:         Admin.TLS.ClientRootCAs = [/var/hyperledger/orderer/tls/ca.crt]
Jan 01 17:02:04 VFIEVOX3.Router 95a3e54eb173[12462]:         Admin.TLS.ClientAuthRequired = true
Jan 01 17:02:04 VFIEVOX3.Router 95a3e54eb173[12462]:         Admin.TLS.RootCAs = [/var/hyperledger/orderer/tls/ca.crt]
Jan 01 17:02:04 VFIEVOX3.Router 95a3e54eb173[12462]:         Admin.TLS.Certificate = "/var/hyperledger/orderer/tls/server.crt"
Jan 01 17:02:04 VFIEVOX3.Router 95a3e54eb173[12462]:         Admin.TLS.PrivateKey = "/var/hyperledger/orderer/tls/server.key"
Jan 01 17:02:04 VFIEVOX3.Router 95a3e54eb173[12462]:         Admin.TLS.Enabled = true
Jan 01 17:02:04 VFIEVOX3.Router 95a3e54eb173[12462]:         Admin.ListenAddress = "0.0.0.0:7053"
Jan 01 17:02:04 VFIEVOX3.Router 95a3e54eb173[12462]:         ChannelParticipation.MaxRequestBodySize = 1048576
Jan 01 17:02:04 VFIEVOX3.Router 95a3e54eb173[12462]:         ChannelParticipation.Enabled = true
Jan 01 17:02:04 VFIEVOX3.Router 95a3e54eb173[12462]:         Metrics.Statsd.Prefix = ""
Jan 01 17:02:04 VFIEVOX3.Router 95a3e54eb173[12462]:         Metrics.Statsd.WriteInterval = 30s
Jan 01 17:02:04 VFIEVOX3.Router 95a3e54eb173[12462]:         Metrics.Statsd.Address = "127.0.0.1:8125"
Jan 01 17:02:04 VFIEVOX3.Router 95a3e54eb173[12462]:         Metrics.Statsd.Network = "udp"
Jan 01 17:02:04 VFIEVOX3.Router 95a3e54eb173[12462]:         Metrics.Provider = "prometheus"
Jan 01 17:02:04 VFIEVOX3.Router 95a3e54eb173[12462]:         Operations.TLS.TLSHandshakeTimeShift = 0s
Jan 01 17:02:04 VFIEVOX3.Router 95a3e54eb173[12462]:         Operations.TLS.ClientRootCAs = []
Jan 01 17:02:04 VFIEVOX3.Router 95a3e54eb173[12462]:         Operations.TLS.ClientAuthRequired = false
Jan 01 17:02:04 VFIEVOX3.Router 95a3e54eb173[12462]:         Operations.TLS.RootCAs = []
Jan 01 17:02:04 VFIEVOX3.Router 95a3e54eb173[12462]:         Operations.TLS.Certificate = ""
Jan 01 17:02:04 VFIEVOX3.Router 95a3e54eb173[12462]:         Operations.TLS.PrivateKey = ""
Jan 01 17:02:04 VFIEVOX3.Router 95a3e54eb173[12462]:         Operations.TLS.Enabled = false
Jan 01 17:02:04 VFIEVOX3.Router 95a3e54eb173[12462]:         Operations.ListenAddress = "orderer.example.com:9443"
Jan 01 17:02:04 VFIEVOX3.Router 95a3e54eb173[12462]:         Consensus = map[SnapDir:/var/hyperledger/production/orderer/etcdraft/snapshot WALDir:/var/hyperledger/production/orderer/etcdraft/wal]
Jan 01 17:02:04 VFIEVOX3.Router 95a3e54eb173[12462]:         Debug.DeliverTraceDir = ""
Jan 01 17:02:04 VFIEVOX3.Router 95a3e54eb173[12462]:         Debug.BroadcastTraceDir = ""
Jan 01 17:02:04 VFIEVOX3.Router 95a3e54eb173[12462]:         Kafka.Topic.ReplicationFactor = 3
Jan 01 17:02:04 VFIEVOX3.Router 95a3e54eb173[12462]:         Kafka.SASLPlain.Password = ""
Jan 01 17:02:04 VFIEVOX3.Router 95a3e54eb173[12462]:         Kafka.SASLPlain.User = ""
Jan 01 17:02:04 VFIEVOX3.Router 95a3e54eb173[12462]:         Kafka.SASLPlain.Enabled = false
Jan 01 17:02:04 VFIEVOX3.Router 95a3e54eb173[12462]:         Kafka.TLS.TLSHandshakeTimeShift = 0s
Jan 01 17:02:04 VFIEVOX3.Router 95a3e54eb173[12462]:         Kafka.TLS.ClientRootCAs = []
Jan 01 17:02:04 VFIEVOX3.Router 95a3e54eb173[12462]:         Kafka.TLS.ClientAuthRequired = false
Jan 01 17:02:04 VFIEVOX3.Router 95a3e54eb173[12462]:         Kafka.TLS.RootCAs = []
Jan 01 17:02:04 VFIEVOX3.Router 95a3e54eb173[12462]:         Kafka.TLS.Certificate = ""
Jan 01 17:02:04 VFIEVOX3.Router 95a3e54eb173[12462]:         Kafka.TLS.PrivateKey = ""
```

**Comment by dbadoy** [comment]
panic: Failed to get local msp config: could not initialize BCCSP Factories: Failed initializing BCCSP: Could not initialize BCCSP SW [Failed to initialize software key store: open /var/hyperledger/orderer/msp/keystore: permission denied]

try that change permissions or owner, group

**Comment by AyushRaj8271** [comment]
Hey, @jkvargas I would suggest you re-download the fabric samples files and try again. Because there might have been some l issues with been some issues with the files you are currently using

**Comment by bestbeforetoday** [comment]
Closing since this issue is very old and the test-network is currently working fine for me with Fabric v2.5 and v3.0.
