### ISSUE TITLE
test-network-k8s: Connection profile using gateway service for peer high availability

### ISSUE THREAD

**Issue by charalarg** [hyperledger/fabric-samples#635]
I am trying to configure the connection profile in order to connect in the gateway-svc as mentioned in [HIGH_AVAILABILITY](https://github.com/hyperledger/fabric-samples/blob/main/test-network-k8s/docs/HIGH_AVAILABILITY.md) file. 
I am sure that i am totally missing something because i am getting the errors described bellow.
I would appreciate if someone could give me some directions or hints in order to implement this. Thank you in advance!

Error log from the application log file that uses the connection profile options:
```
2022-02-08T13:19:24.972Z - error: [ServiceEndpoint]: Error: Failed to connect before the deadline on Endorser- name: org1-peer-gateway-svc, url:grpcs://org1-peer-gateway-svc:7051, connected:false, connectAttempted:true
2022-02-08T13:19:24.975Z - error: [ServiceEndpoint]: waitForReady - Failed to connect to remote gRPC server org1-peer-gateway-svc url:grpcs://org1-peer-gateway-svc:7051 timeout:100000
2022-02-08T13:19:25.034Z - info: [NetworkConfig]: buildPeer - Unable to connect to the endorser org1-peer-gateway-svc due to Error: 
Failed to connect before the deadline on Endorser- name: org1-peer-gateway-svc, url:grpcs://org1-peer-gateway-svc:7051, connected:false, connectAttempted:true
    at checkState (/app/node_modules/@grpc/grpc-js/src/client.ts:172:18)
    at Timeout._onTimeout (/app/node_modules/@grpc/grpc-js/src/channel.ts:708:9)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7) {
  connectFailed: true
}
```
Error log in the peers log files:
```
2022-02-08 13:24:51.423 UTC 0612 ERRO [core.comm] ServerHandshake -> Server TLS handshake failed in 32.620981ms with error EOF server=PeerServer remoteaddress=10.244.0.32:33702
2022-02-08 13:24:53.706 UTC 0613 ERRO [core.comm] ServerHandshake -> Server TLS handshake failed in 6.420937ms with error EOF server=PeerServer remoteaddress=10.244.0.32:33706
2022-02-08 13:24:58.274 UTC 0614 ERRO [core.comm] ServerHandshake -> Server TLS handshake failed in 7.273443ms with error EOF server=PeerServer remoteaddress=10.244.0.32:33710
2022-02-08 13:25:10.115 UTC 0615 ERRO [core.comm] ServerHandshake -> Server TLS handshake failed in 6.862989ms with error EOF server=PeerServer remoteaddress=10.244.0.32:33714
```

Connection profile config options regarding the organizations and peers:
```
"organizations": {
  "Org1": {
    "mspid": "Org1MSP",
    "peers": [
      "org1-peers"
    ],
    "certificateAuthorities": [
      "org1-ca"
    ]
  }
},
"peers": {
  "org1-peers": {
    "url": "grpcs://org1-peer-gateway-svc:7051",
    "tlsCACerts": {
      "pem": "-----BEGIN CERTIFICATE-----\nMIIBdjCC . . . L7KBr\n-----END CERTIFICATE-----\n"
    },
    "grpcOptions": {
      "ssl-target-name-override": "org1-peer-gateway-svc",
      "hostnameOverride": "org1-peer-gateway-svc"
    }
  }
},
```

**Comment by jkneubuh** [comment]
Fixed with PR #639  

Thanks @charalarg !
