### ISSUE TITLE
Kube test network : error when creating channel genesis block

### ISSUE THREAD

**Issue by jkneubuh** [hyperledger/fabric-samples#708]
When installing the kube test network on a Vagrant virtual machine, the network script fails with an error when generating the channel genesis block.

During `network channel create`: 

```
2022-04-07 16:05:28.703 UTC 0003 INFO [common.tools.configtxgen.localconfig] Load -> Loaded configuration: /home/vagrant/fabric-samples/test-network-k8s/config/org0/configtx.yaml
2022-04-07 16:05:28.704 UTC 0004 WARN [msp] getPemMaterialFromDir -> Failed reading file /home/vagrant/fabric-samples/test-network-k8s/build/channel-msp/ordererOrganizations/org0/msp/cacerts/ca-signcert.pe
m: no pem content for file /home/vagrant/fabric-samples/test-network-k8s/build/channel-msp/ordererOrganizations/org0/msp/cacerts/ca-signcert.pem
2022-04-07 16:05:28.704 UTC 0005 PANI [common.tools.configtxgen] func1 -> proto: Marshal called with nil
panic: proto: Marshal called with nil [recovered]
	panic: proto: Marshal called with nil

goroutine 1 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc000448d80, {0x0, 0x0, 0x0})
	/__w/1/go/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/zapcore/entry.go:234 +0x499
go.uber.org/zap.(*SugaredLogger).log(0xc000308248, 0x4, {0xc000487d20, 0xc0005698b0}, {0x0, 0xc000487d00, 0x1e}, {0x0, 0x0, 0x0})
	/__w/1/go/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/sugar.go:234 +0x13b
go.uber.org/zap.(*SugaredLogger).Panicf(...)
	/__w/1/go/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/sugar.go:159
github.com/hyperledger/fabric/common/flogging.(*FabricLogger).Panic(0xc000308250, {0xc000569880, 0xaa4b9b, 0x16})
	/__w/1/go/src/github.com/hyperledger/fabric/common/flogging/zap.go:73 +0x5d
main.main.func1()
	/__w/1/go/src/github.com/hyperledger/fabric/cmd/configtxgen/main.go:261 +0x1b1
panic({0x9dae60, 0xc0000483a0})
	/usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/hyperledger/fabric/protoutil.MarshalOrPanic(...)
	/__w/1/go/src/github.com/hyperledger/fabric/protoutil/commonutils.go:26
github.com/hyperledger/fabric/internal/configtxgen/encoder.addValue(0xc00009a3c0, {0xb5c460, 0xc0001ae7e0}, {0xa99a2a, 0x6})
	/__w/1/go/src/github.com/hyperledger/fabric/internal/configtxgen/encoder/encoder.go:59 +0x14c
github.com/hyperledger/fabric/internal/configtxgen/encoder.NewOrdererOrgGroup(0xc0000f7cb0)
	/__w/1/go/src/github.com/hyperledger/fabric/internal/configtxgen/encoder/encoder.go:270 +0x1bb
github.com/hyperledger/fabric/internal/configtxgen/encoder.NewOrdererGroup(0xc0000f7c20)
	/__w/1/go/src/github.com/hyperledger/fabric/internal/configtxgen/encoder/encoder.go:217 +0x789
github.com/hyperledger/fabric/internal/configtxgen/encoder.NewChannelGroup(0xc000081e40)
	/__w/1/go/src/github.com/hyperledger/fabric/internal/configtxgen/encoder/encoder.go:154 +0x42c
github.com/hyperledger/fabric/internal/configtxgen/encoder.NewBootstrapper(0x0)
	/__w/1/go/src/github.com/hyperledger/fabric/internal/configtxgen/encoder/encoder.go:595 +0xa5
main.doOutputBlock(0xc000081e40, {0x7ffea838b340, 0x9}, {0x7ffea838b357, 0x44})
	/__w/1/go/src/github.com/hyperledger/fabric/cmd/configtxgen/main.go:35 +0x45
main.main()
	/__w/1/go/src/github.com/hyperledger/fabric/cmd/configtxgen/main.go:296 +0x9b2
+ exit_fn
+ rc=2
+ set +x
```

Steps to reproduce: 

1.  `git clone https://github.com/jt-nti/fabric-devenv.git && cd fabric-devenv` 
2. `vagrant up` 
3. `vagrant ssh` 
4. `git clone https://github.com/hyperledger/fabric-samples.git && cd fabric-samples/test-network-k8s` 
5. `./network kind` 
6. `./network up`
7. `./network channel create` 

==> Terminates with the above stack trace in network-debug.log

**Comment by jkneubuh** [comment]
Before creating the genesis block, the network script is pulling the CA's signing certificates into a local file with curl.   For some reason on this ubuntu VM, the curl command is: 

a) returning error code 60   (this should terminate the script at this point, but it does not - problem #1). 

b) failing to accept the build/cas/org0-ca/tls-cert.pem TLS cert when connecting to the CA.   The TLS cert is issued to the correct hostname, and includes the correct SANs in the certificate.  (problem #2)

```
vagrant@vagrant:~/fabric-samples/test-network-k8s$ curl -vv  --cacert /home/vagrant/fabric-samples/test-network-k8s/build/cas/org0-ca/tls-cert.pem https://org0-ca.vcap.me/cainfo
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to org0-ca.vcap.me (127.0.0.1) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /home/vagrant/fabric-samples/test-network-k8s/build/cas/org0-ca/tls-cert.pem
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Unknown (8):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, Server hello (2):
* SSL certificate problem: unable to get local issuer certificate
* stopped the pause stream!
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```


The certificate "looks OK" (at least it is signed with the correct root CA and issued to the correct SANs): 
```
vagrant@vagrant:~/fabric-samples/test-network-k8s$ cat /home/vagrant/fabric-samples/test-network-k8s/build/cas/org0-ca/tls-cert.pem | openssl x509 -text -nocert 
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            96:68:3a:20:e8:05:2d:db:83:13:92:59:3d:b9:69:56
        Signature Algorithm: ecdsa-with-SHA256
        Issuer: CN = org0.example.com
        Validity
            Not Before: Apr  8 13:25:48 2022 GMT
            Not After : Jul  7 13:25:48 2022 GMT
        Subject: 
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub:
                    04:c9:71:8c:de:d0:a7:f8:1c:57:0d:f0:49:41:b8:
                    88:bf:f4:89:96:0a:49:ad:22:e9:7b:4c:0e:a5:68:
                    8c:b1:74:11:8c:5b:79:11:41:75:8c:ca:01:17:22:
                    48:22:48:9b:24:db:5d:20:28:e7:47:8a:93:1c:51:
                    69:9b:cf:da:c1
                ASN1 OID: prime256v1
                NIST CURVE: P-256
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Authority Key Identifier: 
                keyid:79:C2:FE:ED:E0:4C:68:69:DF:C0:66:0F:87:69:CD:00:D5:7C:3E:37

            X509v3 Subject Alternative Name: critical
                DNS:localhost, DNS:org0-ca, DNS:org0-ca.test-network.svc.cluster.local, DNS:org0-ca.vcap.me, IP Address:127.0.0.1
    Signature Algorithm: ecdsa-with-SHA256
         30:45:02:20:1f:14:d6:cc:2e:0e:d0:ce:99:b7:a8:8c:7e:47:
         10:f9:a0:19:db:9d:4b:5b:69:6b:b8:ec:81:0d:6a:ba:0f:7f:
         02:21:00:d2:3e:bf:3f:cc:f4:1f:c3:41:46:bf:34:fb:a0:c1:
         d6:5b:e8:27:9c:3b:df:b9:3e:2b:04:13:96:0e:9f:08:98
```


What's up, curl?

cc: @jt-nti @mbwhite
