### ISSUE TITLE
run "npm install  " on  asset-transfer-basic/application-gateway-typescript

### ISSUE THREAD

**Issue by Pitfall-cmd** [hyperledger/fabric-samples#831]
## Error:
```
> asset-transfer-basic@1.0.0 prepare
> npm run build


npm ERR! code 243
npm ERR! path /home/ybl/go/src/github.com/hyperledger/fabric-samples/asset-transfer-basic/application-gateway-typescript
npm ERR! command failed
npm ERR! command sh -c npm run build

npm ERR! A complete log of this run can be found in:
**npm ERR!     /root/.npm/_logs/2022-09-15T08_08_51_348Z-debug-0.log**
```
## Content in the 2022-09-15T08_08_51_348Z-debug-0.log is :
```
59 http fetch POST 400 https://registry.npmjs.org/-/npm/v1/security/audits/quick 1190ms
60 verbose audit error HttpErrorGeneral: 400 Bad Request - POST https://registry.npmjs.org/-/npm/v1/security/audits/quick - Bad Request
60 verbose audit error     at /home/ybl/node/lib/node_modules/npm/node_modules/npm-registry-fetch/lib/check-response.js:93:15
60 verbose audit error     at processTicksAndRejections (node:internal/process/task_queues:96:5)
60 verbose audit error     at async Map.[getReport] (/home/ybl/node/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:333:21)
60 verbose audit error     at async Map.run (/home/ybl/node/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:106:19)
60 verbose audit error     at async Arborist.reify (/home/ybl/node/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:158:5)
60 verbose audit error     at async Install.exec (/home/ybl/node/lib/node_modules/npm/lib/commands/install.js:156:5)
60 verbose audit error     at async module.exports (/home/ybl/node/lib/node_modules/npm/lib/cli.js:78:5) {
60 verbose audit error   headers: [Object: null prototype] {
60 verbose audit error     date: [ 'Thu, 15 Sep 2022 08:11:03 GMT' ],
60 verbose audit error     'content-type': [ 'application/json; charset=utf-8' ],
60 verbose audit error     'content-length': [ '126' ],
60 verbose audit error     connection: [ 'keep-alive' ],
60 verbose audit error     'cf-ray': [ '74afe3b17bbf9bdc-FRA' ],
60 verbose audit error     'cache-control': [ 'no-cache' ],
60 verbose audit error     vary: [ 'origin, Accept-Encoding' ],
60 verbose audit error     'cf-cache-status': [ 'DYNAMIC' ],
60 verbose audit error     'access-control-allow-credentials': [ 'true' ],
60 verbose audit error     'access-control-expose-headers': [ 'Content-Type,Content-Length' ],
60 verbose audit error     server: [ 'cloudflare' ],
60 verbose audit error     'x-fetch-attempts': [ '1' ]
60 verbose audit error   },
60 verbose audit error   statusCode: 400,
60 verbose audit error   code: 'E400',
60 verbose audit error   method: 'POST',
60 verbose audit error   uri: 'https://registry.npmjs.org/-/npm/v1/security/audits/quick',
60 verbose audit error   body: {
60 verbose audit error     statusCode: 400,
60 verbose audit error     error: 'Bad Request',
60 verbose audit error     message: 'Invalid package tree, run  npm install  to rebuild your package-lock.json'
60 verbose audit error   },
60 verbose audit error   pkgid: undefined
60 verbose audit error }
61 silly audit error [object Object]
62 timing auditReport:getReport Completed in 132146ms
63 silly audit report null
64 timing reify:audit Completed in 132146ms
65 timing reify Completed in 132301ms
66 timing command:install Completed in 132520ms
67 verbose stack Error: command failed
67 verbose stack     at ChildProcess.<anonymous> (/home/ybl/node/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:63:27)
67 verbose stack     at ChildProcess.emit (node:events:527:28)
67 verbose stack     at maybeClose (node:internal/child_process:1092:16)
67 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
68 verbose pkgid asset-transfer-basic@1.0.0
69 verbose cwd /home/ybl/go/src/github.com/hyperledger/fabric-samples/asset-transfer-basic/application-gateway-typescript
70 verbose Linux 5.4.0-84-generic
71 verbose node v16.16.0
72 verbose npm  v8.11.0
73 error code 243
74 error path /home/ybl/go/src/github.com/hyperledger/fabric-samples/asset-transfer-basic/application-gateway-typescript
75 error command failed
76 error command sh -c npm run build
77 verbose exit 243
78 timing npm Completed in 132596ms
79 verbose code 243
80 error A complete log of this run can be found in:
80 error     /root/.npm/_logs/2022-09-15T08_08_51_348Z-debug-0.log

```

**Comment by TruongGiaThach** [comment]
downgrade your node version to 14

**Comment by mbwhite** [comment]
Hello- thanks for taking the time to open an issue. 

I've tried with Node v16 just now and it's all good... Sometimes there are network 'blips' that upset npm.  General advice is to remove the node_modules and re-run.   Though generally you want to keep the package-lock.json, but there is always the chance of this becoming corrupt... therefore there's no harm in deleting this as well. 

Please re-open if this doesn't solve your problem.
